openapi: 3.0.1
info:
  title: My API
  description: An ecommerce sample demonstrating restdocs-api-spec
  version: 0.1.0
servers:
- url: http://localhost:9020
tags: []
paths:
  /sample:
    get:
      tags:
      - 테스트
      summary: Get 테스트
      description: Get 테스트
      operationId: test-get
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MainResponse'
              examples:
                test-get:
                  value: |-
                    {
                      "message" : "get test success"
                    }
  /sample/post:
    post:
      tags:
      - 테스트- post body
      summary: Post 테스트- body
      description: Post 테스트- body
      operationId: post param
      parameters:
      - name: message
        in: query
        description: message
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
components:
  schemas:
    MainResponse:
      title: MainResponse
      type: object
      properties:
        message:
          type: string
          description: 메세지
