openapi: 3.0.1
info:
  title: My API
  description: An ecommerce sample demonstrating restdocs-api-spec
  version: 0.1.0
servers:
- url: https://localhost:8080
tags: []
paths:
  /user:
    get:
      tags:
      - 테스트
      summary: Get 테스트
      description: Get 테스트
      operationId: test-get
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MainResponse.Get'
              examples:
                test-get:
                  value: |-
                    {
                      "message" : "get test success"
                    }
components:
  schemas:
    MainResponse.Get:
      title: MainResponse.Get
      type: object
      properties:
        message:
          type: string
          description: 메세지
