openapi: 3.0.1
info:
  title: Rest doc API
  description: not security sample demonstrating restdocs-api-spec
  version: 0.1.0
servers:
- url: http://localhost:9010
tags: []
paths:
  /lecture:
    get:
      tags:
      - 수강신청
      summary: 수강신청
      description: 수강신청 테스트
      operationId: lecture-list
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lecture957993693'
              examples:
                lecture-list:
                  value: "[ ]"
    post:
      tags:
      - 수강신청
      summary: 수강신청
      description: 수강신청 저장
      operationId: lecture save
      parameters:
      - name: name
        in: query
        description: 수강과목
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lecture-741699920'
              examples:
                lecture save:
                  value: |-
                    [ {
                      "seq" : 1,
                      "name" : "수학"
                    } ]
  /sample:
    get:
      tags:
      - 테스트
      summary: Get 테스트
      description: Get 테스트
      operationId: test-get
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MainResponse'
              examples:
                test-get:
                  value: |-
                    {
                      "message" : "get test success"
                    }
    post:
      tags:
      - 테스트- post body
      summary: Post 테스트- body
      description: Post 테스트- body
      operationId: post param
      parameters:
      - name: message
        in: query
        description: message
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
  /sample/dto:
    post:
      tags:
      - 테스트- post dto
      summary: Post 테스트- dto
      description: Post 테스트- dto
      operationId: post dto
      parameters:
      - name: message
        in: query
        description: message
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
  /sample/list:
    get:
      tags:
      - 테스트- list dto
      summary: list dto 테스트- dto
      description: list 테스트- dto
      operationId: list dto
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sample-list-10996445'
              examples:
                list dto:
                  value: "[ ]"
  /sample/param:
    get:
      tags:
      - 테스트- get param
      summary: Get 테스트- param
      description: Get 테스트- param
      operationId: get param
      parameters:
      - name: userId
        in: query
        description: user id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
  /sample/get/{userId}:
    get:
      tags:
      - 테스트- get path
      summary: Get 테스트- path
      description: Get 테스트- path
      operationId: get path
      parameters:
      - name: userId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
components:
  schemas:
    lecture957993693:
      type: array
      description: 수강신청 리스트
      items:
        oneOf:
        - type: object
        - type: boolean
        - type: string
        - type: number
    lecture-741699920:
      type: array
      description: 수강신청 과목 리스트
      items:
        type: object
        properties:
          name:
            type: string
            description: 수강신청 명
          seq:
            type: number
            description: 수강신청 seq
        description: 수강신청 과목 리스트
    sample-list-10996445:
      type: array
      description: 리턴데이터
      items:
        oneOf:
        - type: object
        - type: boolean
        - type: string
        - type: number
    MainResponse:
      title: MainResponse
      type: object
      properties:
        message:
          type: string
          description: 메세지
